import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import './globals.css';
import { Provider } from '@/Provider';
import { ClerkProvider } from '@clerk/nextjs';
import { Toaster } from 'sonner';
import { Suspense } from 'react';
import Loading from '@/components/Loading';

const dm_sans = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-dm-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body className={`${dm_sans.className} antialiased`}>
          <Provider>
            <Suspense fallback={<Loading />}>
              <div className="root-layout">{children}</div>
              <Toaster />
            </Suspense>
          </Provider>
        </body>
      </ClerkProvider>
    </html>
  );
}
